# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: python --version
  run-pylint:
    docker:
      - image: cimg/python:3.10.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install pylint"
          command: "pip install pylint"
      - run:
          name: "Lint using pylint"
          command: "python -m pylint calc.py --variable-naming-style=snake_case --function-naming-style=snake_case"
  lint-commit-messages:
    docker:
      - image: cimg/node:17.0.1
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Verify node/npm version"
          command: "node -v && npm -v"
      - run:
          name: "Install dependencies"
          command: "yarn global add @s-libs/ng-core @s-libs/rxjs-core @s-libs/js-core @s-libs/micro-dash @angular/cdk @angular/cli @angular/core@12.0.0 @angular/common@13.0.0 jasmine-core@3.6.0 rxjs@6.5.3 zone.js@0.11.4 && yarn add -D @s-libs/ng-dev"
      - run:
          name: "Lint commit messages using ng-dev"
          command: "yarn -s ng-dev commit-message validate-range $CI_GIT_BASE_REVISION $CI_GIT_REVISION"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  lint-py:
    jobs:
      - build
      - run-pylint:
         requires:
          - build
  lint-commit-messages:
    jobs:
      - lint-commit-messages
